version: '3'

services:
  app_vet:
    build: MyFirstProject
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://juancho_crud:3307/misproductos?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: juancho1106
    restart: always
    depends_on:
      juancho_crud:
        condition: service_healthy

  juancho_crud:
    image: mysql:8.0.38
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: misproductos
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
